export interface CurrencyInfo {
  code: string;
  name: string;
  nameNb: string;
  flag: string;
}

// Common currencies pinned at top
export const COMMON_CURRENCY_CODES = [
  "NOK", "EUR", "USD", "GBP", "SEK", "DKK", "CHF", "JPY", "CAD", "AUD", "THB", "PLN", "CZK", "HUF", "TRY",
];

export const currencies: CurrencyInfo[] = [
  { code: "AED", name: "UAE Dirham", nameNb: "Emiratisk dirham", flag: "🇦🇪" },
  { code: "AFN", name: "Afghan Afghani", nameNb: "Afghansk afghani", flag: "🇦🇫" },
  { code: "ALL", name: "Albanian Lek", nameNb: "Albansk lek", flag: "🇦🇱" },
  { code: "AMD", name: "Armenian Dram", nameNb: "Armensk dram", flag: "🇦🇲" },
  { code: "ANG", name: "Netherlands Antillean Guilder", nameNb: "Nederlandsk-antillisk gylden", flag: "🇨🇼" },
  { code: "AOA", name: "Angolan Kwanza", nameNb: "Angolansk kwanza", flag: "🇦🇴" },
  { code: "ARS", name: "Argentine Peso", nameNb: "Argentinsk peso", flag: "🇦🇷" },
  { code: "AUD", name: "Australian Dollar", nameNb: "Australsk dollar", flag: "🇦🇺" },
  { code: "AWG", name: "Aruban Florin", nameNb: "Arubansk florin", flag: "🇦🇼" },
  { code: "AZN", name: "Azerbaijani Manat", nameNb: "Aserbajdsjansk manat", flag: "🇦🇿" },
  { code: "BAM", name: "Bosnia-Herzegovina Mark", nameNb: "Bosnisk mark", flag: "🇧🇦" },
  { code: "BBD", name: "Barbadian Dollar", nameNb: "Barbadisk dollar", flag: "🇧🇧" },
  { code: "BDT", name: "Bangladeshi Taka", nameNb: "Bangladeshisk taka", flag: "🇧🇩" },
  { code: "BGN", name: "Bulgarian Lev", nameNb: "Bulgarsk lev", flag: "🇧🇬" },
  { code: "BHD", name: "Bahraini Dinar", nameNb: "Bahrainske dinar", flag: "🇧🇭" },
  { code: "BIF", name: "Burundian Franc", nameNb: "Burundisk franc", flag: "🇧🇮" },
  { code: "BMD", name: "Bermudan Dollar", nameNb: "Bermudisk dollar", flag: "🇧🇲" },
  { code: "BND", name: "Brunei Dollar", nameNb: "Bruneisk dollar", flag: "🇧🇳" },
  { code: "BOB", name: "Bolivian Boliviano", nameNb: "Boliviansk boliviano", flag: "🇧🇴" },
  { code: "BRL", name: "Brazilian Real", nameNb: "Brasiliansk real", flag: "🇧🇷" },
  { code: "BSD", name: "Bahamian Dollar", nameNb: "Bahamansk dollar", flag: "🇧🇸" },
  { code: "BTN", name: "Bhutanese Ngultrum", nameNb: "Bhutansk ngultrum", flag: "🇧🇹" },
  { code: "BWP", name: "Botswanan Pula", nameNb: "Botswansk pula", flag: "🇧🇼" },
  { code: "BYN", name: "Belarusian Ruble", nameNb: "Hviterussisk rubel", flag: "🇧🇾" },
  { code: "BZD", name: "Belize Dollar", nameNb: "Belizisk dollar", flag: "🇧🇿" },
  { code: "CAD", name: "Canadian Dollar", nameNb: "Kanadisk dollar", flag: "🇨🇦" },
  { code: "CDF", name: "Congolese Franc", nameNb: "Kongolesisk franc", flag: "🇨🇩" },
  { code: "CHF", name: "Swiss Franc", nameNb: "Sveitsisk franc", flag: "🇨🇭" },
  { code: "CLP", name: "Chilean Peso", nameNb: "Chilensk peso", flag: "🇨🇱" },
  { code: "CNY", name: "Chinese Yuan", nameNb: "Kinesisk yuan", flag: "🇨🇳" },
  { code: "COP", name: "Colombian Peso", nameNb: "Colombiansk peso", flag: "🇨🇴" },
  { code: "CRC", name: "Costa Rican Colón", nameNb: "Costaricansk colón", flag: "🇨🇷" },
  { code: "CUP", name: "Cuban Peso", nameNb: "Kubansk peso", flag: "🇨🇺" },
  { code: "CVE", name: "Cape Verdean Escudo", nameNb: "Kappverdisk escudo", flag: "🇨🇻" },
  { code: "CZK", name: "Czech Koruna", nameNb: "Tsjekkisk krone", flag: "🇨🇿" },
  { code: "DJF", name: "Djiboutian Franc", nameNb: "Djiboutisk franc", flag: "🇩🇯" },
  { code: "DKK", name: "Danish Krone", nameNb: "Dansk krone", flag: "🇩🇰" },
  { code: "DOP", name: "Dominican Peso", nameNb: "Dominikansk peso", flag: "🇩🇴" },
  { code: "DZD", name: "Algerian Dinar", nameNb: "Algerisk dinar", flag: "🇩🇿" },
  { code: "EGP", name: "Egyptian Pound", nameNb: "Egyptisk pund", flag: "🇪🇬" },
  { code: "ERN", name: "Eritrean Nakfa", nameNb: "Eritreisk nakfa", flag: "🇪🇷" },
  { code: "ETB", name: "Ethiopian Birr", nameNb: "Etiopisk birr", flag: "🇪🇹" },
  { code: "EUR", name: "Euro", nameNb: "Euro", flag: "🇪🇺" },
  { code: "FJD", name: "Fijian Dollar", nameNb: "Fijiansk dollar", flag: "🇫🇯" },
  { code: "FKP", name: "Falkland Islands Pound", nameNb: "Falklandsk pund", flag: "🇫🇰" },
  { code: "GBP", name: "British Pound", nameNb: "Britisk pund", flag: "🇬🇧" },
  { code: "GEL", name: "Georgian Lari", nameNb: "Georgisk lari", flag: "🇬🇪" },
  { code: "GHS", name: "Ghanaian Cedi", nameNb: "Ghanesisk cedi", flag: "🇬🇭" },
  { code: "GIP", name: "Gibraltar Pound", nameNb: "Gibraltarsk pund", flag: "🇬🇮" },
  { code: "GMD", name: "Gambian Dalasi", nameNb: "Gambisk dalasi", flag: "🇬🇲" },
  { code: "GNF", name: "Guinean Franc", nameNb: "Guineansk franc", flag: "🇬🇳" },
  { code: "GTQ", name: "Guatemalan Quetzal", nameNb: "Guatemalansk quetzal", flag: "🇬🇹" },
  { code: "GYD", name: "Guyanaese Dollar", nameNb: "Guyansk dollar", flag: "🇬🇾" },
  { code: "HKD", name: "Hong Kong Dollar", nameNb: "Hongkongsk dollar", flag: "🇭🇰" },
  { code: "HNL", name: "Honduran Lempira", nameNb: "Honduransk lempira", flag: "🇭🇳" },
  { code: "HRK", name: "Croatian Kuna", nameNb: "Kroatisk kuna", flag: "🇭🇷" },
  { code: "HTG", name: "Haitian Gourde", nameNb: "Haitisk gourde", flag: "🇭🇹" },
  { code: "HUF", name: "Hungarian Forint", nameNb: "Ungarsk forint", flag: "🇭🇺" },
  { code: "IDR", name: "Indonesian Rupiah", nameNb: "Indonesisk rupi", flag: "🇮🇩" },
  { code: "ILS", name: "Israeli Shekel", nameNb: "Israelsk shekel", flag: "🇮🇱" },
  { code: "INR", name: "Indian Rupee", nameNb: "Indisk rupi", flag: "🇮🇳" },
  { code: "IQD", name: "Iraqi Dinar", nameNb: "Irakisk dinar", flag: "🇮🇶" },
  { code: "IRR", name: "Iranian Rial", nameNb: "Iransk rial", flag: "🇮🇷" },
  { code: "ISK", name: "Icelandic Króna", nameNb: "Islandsk krone", flag: "🇮🇸" },
  { code: "JMD", name: "Jamaican Dollar", nameNb: "Jamaicansk dollar", flag: "🇯🇲" },
  { code: "JOD", name: "Jordanian Dinar", nameNb: "Jordansk dinar", flag: "🇯🇴" },
  { code: "JPY", name: "Japanese Yen", nameNb: "Japansk yen", flag: "🇯🇵" },
  { code: "KES", name: "Kenyan Shilling", nameNb: "Kenyansk shilling", flag: "🇰🇪" },
  { code: "KGS", name: "Kyrgystani Som", nameNb: "Kirgisisk som", flag: "🇰🇬" },
  { code: "KHR", name: "Cambodian Riel", nameNb: "Kambodsjansk riel", flag: "🇰🇭" },
  { code: "KMF", name: "Comorian Franc", nameNb: "Komorisk franc", flag: "🇰🇲" },
  { code: "KRW", name: "South Korean Won", nameNb: "Sørkoreansk won", flag: "🇰🇷" },
  { code: "KWD", name: "Kuwaiti Dinar", nameNb: "Kuwaitisk dinar", flag: "🇰🇼" },
  { code: "KYD", name: "Cayman Islands Dollar", nameNb: "Caymansk dollar", flag: "🇰🇾" },
  { code: "KZT", name: "Kazakhstani Tenge", nameNb: "Kasakhstansk tenge", flag: "🇰🇿" },
  { code: "LAK", name: "Laotian Kip", nameNb: "Laotisk kip", flag: "🇱🇦" },
  { code: "LBP", name: "Lebanese Pound", nameNb: "Libanesisk pund", flag: "🇱🇧" },
  { code: "LKR", name: "Sri Lankan Rupee", nameNb: "Srilankisk rupi", flag: "🇱🇰" },
  { code: "LRD", name: "Liberian Dollar", nameNb: "Liberisk dollar", flag: "🇱🇷" },
  { code: "LSL", name: "Lesotho Loti", nameNb: "Lesothisk loti", flag: "🇱🇸" },
  { code: "LYD", name: "Libyan Dinar", nameNb: "Libysk dinar", flag: "🇱🇾" },
  { code: "MAD", name: "Moroccan Dirham", nameNb: "Marokkansk dirham", flag: "🇲🇦" },
  { code: "MDL", name: "Moldovan Leu", nameNb: "Moldovsk leu", flag: "🇲🇩" },
  { code: "MGA", name: "Malagasy Ariary", nameNb: "Gassisk ariary", flag: "🇲🇬" },
  { code: "MKD", name: "Macedonian Denar", nameNb: "Makedonsk denar", flag: "🇲🇰" },
  { code: "MMK", name: "Myanma Kyat", nameNb: "Myanmarsk kyat", flag: "🇲🇲" },
  { code: "MNT", name: "Mongolian Tugrik", nameNb: "Mongolsk tugrik", flag: "🇲🇳" },
  { code: "MOP", name: "Macanese Pataca", nameNb: "Macaoisk pataca", flag: "🇲🇴" },
  { code: "MRU", name: "Mauritanian Ouguiya", nameNb: "Mauritansk ouguiya", flag: "🇲🇷" },
  { code: "MUR", name: "Mauritian Rupee", nameNb: "Mauritisk rupi", flag: "🇲🇺" },
  { code: "MVR", name: "Maldivian Rufiyaa", nameNb: "Maldivisk rufiyaa", flag: "🇲🇻" },
  { code: "MWK", name: "Malawian Kwacha", nameNb: "Malawisk kwacha", flag: "🇲🇼" },
  { code: "MXN", name: "Mexican Peso", nameNb: "Meksikansk peso", flag: "🇲🇽" },
  { code: "MYR", name: "Malaysian Ringgit", nameNb: "Malaysisk ringgit", flag: "🇲🇾" },
  { code: "MZN", name: "Mozambican Metical", nameNb: "Mosambikisk metical", flag: "🇲🇿" },
  { code: "NAD", name: "Namibian Dollar", nameNb: "Namibisk dollar", flag: "🇳🇦" },
  { code: "NGN", name: "Nigerian Naira", nameNb: "Nigeriansk naira", flag: "🇳🇬" },
  { code: "NIO", name: "Nicaraguan Córdoba", nameNb: "Nicaraguansk córdoba", flag: "🇳🇮" },
  { code: "NOK", name: "Norwegian Krone", nameNb: "Norsk krone", flag: "🇳🇴" },
  { code: "NPR", name: "Nepalese Rupee", nameNb: "Nepalsk rupi", flag: "🇳🇵" },
  { code: "NZD", name: "New Zealand Dollar", nameNb: "Newzealandsk dollar", flag: "🇳🇿" },
  { code: "OMR", name: "Omani Rial", nameNb: "Omansk rial", flag: "🇴🇲" },
  { code: "PAB", name: "Panamanian Balboa", nameNb: "Panamansk balboa", flag: "🇵🇦" },
  { code: "PEN", name: "Peruvian Sol", nameNb: "Peruansk sol", flag: "🇵🇪" },
  { code: "PGK", name: "Papua New Guinean Kina", nameNb: "Papuansk kina", flag: "🇵🇬" },
  { code: "PHP", name: "Philippine Peso", nameNb: "Filippinsk peso", flag: "🇵🇭" },
  { code: "PKR", name: "Pakistani Rupee", nameNb: "Pakistansk rupi", flag: "🇵🇰" },
  { code: "PLN", name: "Polish Zloty", nameNb: "Polsk zloty", flag: "🇵🇱" },
  { code: "PYG", name: "Paraguayan Guarani", nameNb: "Paraguayansk guarani", flag: "🇵🇾" },
  { code: "QAR", name: "Qatari Riyal", nameNb: "Qatarsk riyal", flag: "🇶🇦" },
  { code: "RON", name: "Romanian Leu", nameNb: "Rumensk leu", flag: "🇷🇴" },
  { code: "RSD", name: "Serbian Dinar", nameNb: "Serbisk dinar", flag: "🇷🇸" },
  { code: "RUB", name: "Russian Ruble", nameNb: "Russisk rubel", flag: "🇷🇺" },
  { code: "RWF", name: "Rwandan Franc", nameNb: "Rwandisk franc", flag: "🇷🇼" },
  { code: "SAR", name: "Saudi Riyal", nameNb: "Saudisk riyal", flag: "🇸🇦" },
  { code: "SBD", name: "Solomon Islands Dollar", nameNb: "Salomonsk dollar", flag: "🇸🇧" },
  { code: "SCR", name: "Seychellois Rupee", nameNb: "Seychellisk rupi", flag: "🇸🇨" },
  { code: "SDG", name: "Sudanese Pound", nameNb: "Sudansk pund", flag: "🇸🇩" },
  { code: "SEK", name: "Swedish Krona", nameNb: "Svensk krone", flag: "🇸🇪" },
  { code: "SGD", name: "Singapore Dollar", nameNb: "Singaporsk dollar", flag: "🇸🇬" },
  { code: "SHP", name: "Saint Helena Pound", nameNb: "St. Helena-pund", flag: "🇸🇭" },
  { code: "SLE", name: "Sierra Leonean Leone", nameNb: "Sierraleonsk leone", flag: "🇸🇱" },
  { code: "SOS", name: "Somali Shilling", nameNb: "Somalisk shilling", flag: "🇸🇴" },
  { code: "SRD", name: "Surinamese Dollar", nameNb: "Surinamsk dollar", flag: "🇸🇷" },
  { code: "SSP", name: "South Sudanese Pound", nameNb: "Sørsudansk pund", flag: "🇸🇸" },
  { code: "STN", name: "São Tomé and Príncipe Dobra", nameNb: "São Tomésk dobra", flag: "🇸🇹" },
  { code: "SYP", name: "Syrian Pound", nameNb: "Syrisk pund", flag: "🇸🇾" },
  { code: "SZL", name: "Swazi Lilangeni", nameNb: "Swazilandsk lilangeni", flag: "🇸🇿" },
  { code: "THB", name: "Thai Baht", nameNb: "Thailandsk baht", flag: "🇹🇭" },
  { code: "TJS", name: "Tajikistani Somoni", nameNb: "Tadsjikisk somoni", flag: "🇹🇯" },
  { code: "TMT", name: "Turkmenistani Manat", nameNb: "Turkmensk manat", flag: "🇹🇲" },
  { code: "TND", name: "Tunisian Dinar", nameNb: "Tunisisk dinar", flag: "🇹🇳" },
  { code: "TOP", name: "Tongan Paʻanga", nameNb: "Tongansk paʻanga", flag: "🇹🇴" },
  { code: "TRY", name: "Turkish Lira", nameNb: "Tyrkisk lira", flag: "🇹🇷" },
  { code: "TTD", name: "Trinidad & Tobago Dollar", nameNb: "Trinidadisk dollar", flag: "🇹🇹" },
  { code: "TWD", name: "New Taiwan Dollar", nameNb: "Taiwansk dollar", flag: "🇹🇼" },
  { code: "TZS", name: "Tanzanian Shilling", nameNb: "Tanzaniansk shilling", flag: "🇹🇿" },
  { code: "UAH", name: "Ukrainian Hryvnia", nameNb: "Ukrainsk hryvnia", flag: "🇺🇦" },
  { code: "UGX", name: "Ugandan Shilling", nameNb: "Ugandisk shilling", flag: "🇺🇬" },
  { code: "USD", name: "US Dollar", nameNb: "Amerikanske dollar", flag: "🇺🇸" },
  { code: "UYU", name: "Uruguayan Peso", nameNb: "Uruguayansk peso", flag: "🇺🇾" },
  { code: "UZS", name: "Uzbekistan Som", nameNb: "Usbekisk som", flag: "🇺🇿" },
  { code: "VES", name: "Venezuelan Bolívar", nameNb: "Venezuelansk bolívar", flag: "🇻🇪" },
  { code: "VND", name: "Vietnamese Dong", nameNb: "Vietnamesisk dong", flag: "🇻🇳" },
  { code: "VUV", name: "Vanuatu Vatu", nameNb: "Vanuatisk vatu", flag: "🇻🇺" },
  { code: "WST", name: "Samoan Tala", nameNb: "Samoansk tala", flag: "🇼🇸" },
  { code: "XAF", name: "CFA Franc BEAC", nameNb: "CFA-franc BEAC", flag: "🇨🇲" },
  { code: "XCD", name: "East Caribbean Dollar", nameNb: "Østkaribisk dollar", flag: "🇦🇬" },
  { code: "XOF", name: "CFA Franc BCEAO", nameNb: "CFA-franc BCEAO", flag: "🇸🇳" },
  { code: "XPF", name: "CFP Franc", nameNb: "CFP-franc", flag: "🇵🇫" },
  { code: "YER", name: "Yemeni Rial", nameNb: "Jemenittisk rial", flag: "🇾🇪" },
  { code: "ZAR", name: "South African Rand", nameNb: "Sørafrikansk rand", flag: "🇿🇦" },
  { code: "ZMW", name: "Zambian Kwacha", nameNb: "Zambisk kwacha", flag: "🇿🇲" },
  { code: "ZWL", name: "Zimbabwean Dollar", nameNb: "Zimbabwisk dollar", flag: "🇿🇼" },
];

export function getCurrencyInfo(code: string): CurrencyInfo | undefined {
  return currencies.find((c) => c.code === code);
}

export function getCurrencyName(code: string, lang: "nb" | "en"): string {
  const info = getCurrencyInfo(code);
  if (!info) return code;
  return lang === "nb" ? info.nameNb : info.name;
}
